name: Go
on: [push]
jobs:

  build:
    name: Test Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    env:
      go_latest: 'stable'
    strategy:
      matrix:
        go:
        - 'stable'
        - 'oldstable'
        - '1.25'
        - '1.24'
        - '1.23'
        - '1.22'
        - '1.21'
        - '1.20'
        - '1.19'
        - '1.18'
        - '1.17'
        - '1.16'
        - '1.15'
        - '1.14'
        - '1.13'

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v7

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v7
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: go test -race -v -coverprofile=.coverage.out -covermode=atomic ./...

    # https://app.codecov.io/github.com/dolmen-go/jsonptr
    - name: Upload coverage to Codecov
      if: matrix.go == env.go_latest
      uses: codecov/codecov-action@v7
      with:
        disable_search: true
        files: ./.coverage.out
        disable_telem: true
        report_type: coverage
        fail_ci_if_error: true
        # https://app.codecov.io/gh/dolmen-go/jsonptr/config/general
        # https://github.com/dolmen-go/jsonptr/settings/secrets/actions
        token: ${{ secrets.CODECOV_TOKEN }}
