name: Go
on: [push]
jobs:

  build:
    name: Test Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    env:
      go_latest: '1.20'
    strategy:
      matrix:
        go:
        - '1.20'
        - '1.19'
        - '1.18'
        - '1.17'
        - '1.16'
        - '1.15'
        - '1.14'
        - '1.13'
        - '1.12'

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

    # https://app.codecov.io/github.com/dolmen-go/jsonptr
    - name: Upload coverage to Codecov
      if: matrix.go == env.go_latest
      uses: codecov/codecov-action@v3
